# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "eurolinux-vagrant/centos-stream-8"
    config.vm.hostname = "zabbixvm"
    config.vm.network "private_network", ip: "192.168.56.20"
    
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
      
    end
  
    config.vm.provision "shell", path: "D:/vagrant-zabbix/vagrant-zabbix/centos8-zabbix-server/zabbix-mysql.sh"
    
  end
  