Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.hostname = "ubuntu"
    config.vm.network "private_network", ip: "192.168.56.14"
    
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  
    #config.vm.provision "shell", path: "D:/vagrant-zabbix/vagrant-zabbix/ubuntu-zabbix-server/zabbix-mysql.sh"
    
  end
  